Repository JordiWillyam/Aplikasi-Pemesanan-Paket-Wisata-Kusuma, pull requests merged in 2024-09, with the labels that each got.

#1 ADD : Header Paket Wisata
  HalamanUtama.html
Labels: documentation

#2 ADD : Title pada Formulir Pemesanan 1
  HalamanFormulirBangka.html
Labels: enhancement

#3 ADD : Label Nama Lengkap dan Email
  HalamanFormulirBangka.html
Labels: enhancement

#4 ADD : Label telepon dan tanggal
  HalamanFormulirBangka.html
Labels: enhancement

#5 ADD : Tombol Pesan Sekarang
  HalamanFormulirBangka.html
Labels: enhancement, question

#6 ADD : css style
  HalamanFormulirBangka.html
Labels: enhancement

#7 ADD : Script untuk tanggal
  HalamanFormulirBangka.html
Labels: enhancement

#8 Feature/halaman pemesanan
  detailPemesananBangka.html
Labels: enhancement

#9 ADD : Halaman Pemesanan Paket Bangka
  detailPemesananBangka.html
  pemesananBangkaBehasil.html
Labels: enhancement

#10 ADD : Title Formulir Wisata Bandung
  HalamanFormulirBandung.html
Labels: enhancement

#12 ADD : Style
  HalamanFormulirBandung.html
Labels: enhancement

#14 ADD : Formulir Wisata NTT
  HalamanFormulirBandung.html
  HalamanFormulirBangka.html
  HalamanFormulirNTT.html
Labels: enhancement

#15 ADD : Value to Tanggal
  HalamanFormulirBandung.html
Labels: enhancement

#17 ADD : Detail Pemesanan Bandung
  detailPemesananBandung.html
  pemesananBangkaBehasil.html
Labels: enhancement

#20 CHANGE : href dan file pemesananBangkaBerhasil
  detailPemesananBandung.html
  detailPemesananBangka.html
  pemesananBehasil.html
Labels: enhancement

#22 CHANGE : Data Konsumen Bandung dan NTT
  HalamanFormulirBandung.html
  HalamanFormulirNTT.html
Labels: duplicate

#25 UPDATE : Form Action Into Detail Pemesanan
  HalamanFormulirBandung.html
  HalamanFormulirBangka.html
  HalamanFormulirNTT.html
Labels: duplicate

#28 UPDATE : menambahkan button
  HalamanUtama.html
Labels: enhancement

#29 UPDATE : membuat button NTT
  HalamanUtama.html
Labels: enhancement

#30 UPDATE : Perubahan css
  HalamanUtama.html
Labels: documentation

#32 UPDATE : style for all formulir
  HalamanFormulirBandung.html
  HalamanFormulirBangka.html
  HalamanFormulirNTT.html
Labels: enhancement
